import { useRef } from "react";

import html2canvas from "html2canvas";

import Sidebar from "../components/Sidebar";
import Topbar from "../components/Topbar";

import SalesReportCard
from "../components/SalesReportCard";

import "../styles/sales.css";

export default function Sales({ goTo }) {

  const reportRef = useRef();

  /* SALES */

  const sales =
    JSON.parse(
      localStorage.getItem("sales")
    ) || [];

  /* STORE SETTINGS */

  const storeSettings =
    JSON.parse(
      localStorage.getItem(
        "storeSettings"
      )
    ) || {};

  /* ACTIVE BRANCH */

  const activeBranch =
    localStorage.getItem(
      "activeBranch"
    ) || "Main Branch";

  /* TOTAL REVENUE */

  const revenue = sales.reduce(
    (acc, sale) =>
      acc + parseFloat(sale.total),
    0
  );

  /* CARD PAYMENTS */

  const cardPayments =
    sales.filter(
      (sale) =>
        sale.paymentMethod === "Card"
    ).length;

  /* CASH PAYMENTS */

  const cashPayments =
    sales.filter(
      (sale) =>
        sale.paymentMethod === "Cash"
    ).length;

  /* AVG TICKET */

  const averageTicket =
    sales.length > 0
      ? revenue / sales.length
      : 0;

  /* TOP PRODUCT */

  const productCount = {};

  sales.forEach((sale) => {

    sale.items.forEach((item) => {

      if (!productCount[item.name]) {

        productCount[item.name] = 0;
      }

      productCount[item.name] += item.quantity;

    });

  });

  const topProduct =
    Object.keys(productCount).length > 0

      ? Object.keys(productCount).reduce(
          (a, b) =>
            productCount[a] >
            productCount[b]
              ? a
              : b
        )

      : "No Products";

  /* REPORT TEXT */

  const reportText = `

EL CORDOBÉS POS

DAILY SALES SUMMARY

Brand:
${storeSettings.shopName || "Coffee Shop"}

Branch:
${activeBranch}

Revenue:
$${revenue.toFixed(2)} MXN

Orders:
${sales.length}

Average Ticket:
$${averageTicket.toFixed(2)} MXN

Card Payments:
${cardPayments}

Cash Payments:
${cashPayments}

Top Product:
${topProduct}

Generated by EL CORDOBÉS POS
`;

  /* SHARE REPORT */

  const exportReportImage =
    async () => {

    const canvas =
      await html2canvas(
        reportRef.current
      );

    canvas.toBlob(
      async (blob) => {

      const file =
        new File(

          [blob],

          "sales-report.png",

          {
            type: "image/png"
          }

        );

      /* MOBILE SHARE */

      if (

        navigator.share &&

        navigator.canShare({
          files:[file]
        })

      ) {

        await navigator.share({

          title:
            "Daily Sales Report",

          text:
            reportText,

          files:[file]

        });

      } else {

        /* DESKTOP DOWNLOAD */

        const image =
          canvas.toDataURL(
            "image/png"
          );

        const link =
          document.createElement(
            "a"
          );

        link.href = image;

        link.download =
          "sales-report.png";

        link.click();
      }

    });
  };

  return (

    <div className="dashboard-layout">

      <Sidebar
        goTo={goTo}
        active="sales"
      />

      <main className="dashboard-main">

        <Topbar
          title="Sales"
          subtitle="SALES ANALYTICS"
        />

        {/* STATS */}

        <section className="sales-stats-grid">

          <div className="sales-stat-card">

            <span>
              Total Revenue
            </span>

            <h2>
              ${revenue.toFixed(2)}
            </h2>

          </div>

          <div className="sales-stat-card">

            <span>
              Orders
            </span>

            <h2>
              {sales.length}
            </h2>

          </div>

          <div className="sales-stat-card">

            <span>
              Card Payments
            </span>

            <h2>
              {cardPayments}
            </h2>

          </div>

          <div className="sales-stat-card">

            <span>
              Cash Payments
            </span>

            <h2>
              {cashPayments}
            </h2>

          </div>

          <div className="sales-stat-card">

            <span>
              Avg Ticket
            </span>

            <h2>
              ${averageTicket.toFixed(2)}
            </h2>

          </div>

        </section>

        {/* REPORT CARD */}

        <div ref={reportRef}>

          <SalesReportCard

            revenue={revenue}

            orders={sales.length}

            averageTicket={averageTicket}

            cardPayments={cardPayments}

            cashPayments={cashPayments}

            topProduct={topProduct}

            storeSettings={storeSettings}

            activeBranch={activeBranch}

          />

        </div>

        {/* ACTIONS */}

        <section className="report-actions">

          <button
            className="report-btn"

            onClick={() => {

              navigator.clipboard.writeText(
                reportText
              );

              alert(
                "Report Copied"
              );

            }}
          >

            Copy Report

          </button>

          <button
            className="report-btn"

            onClick={
              exportReportImage
            }
          >

            Share Report

          </button>

        </section>

        {/* SALES HISTORY */}

        <section className="sales-history">

          <div className="section-title">

            <h2>
              Sales History
            </h2>

          </div>

          <div className="sales-history-list">

            {sales.length === 0 && (

              <p className="empty-sales">

                No sales yet

              </p>

            )}

            {sales.map((sale, index) => (

              <div
                key={index}
                className="history-card"
              >

                {/* LEFT */}

                <div className="history-left">

                  <h3>
                    ORDER #{sale.orderNumber}
                  </h3>

                  <p>
                    {sale.customerName ||
                      "Guest"}
                  </p>

                  <span>
                    {sale.date}
                  </span>

                </div>

                {/* CENTER */}

                <div className="history-center">

                  {sale.items.map(
                    (item, itemIndex) => (

                      <div
                        key={itemIndex}
                        className="history-item"
                      >

                        {item.quantity}x{" "}
                        {item.name}

                      </div>

                    )
                  )}

                </div>

                {/* RIGHT */}

                <div className="history-right">

                  <h2>
                    ${sale.total}
                  </h2>

                  <div className="payment-badge">

                    {sale.paymentMethod}

                  </div>

                </div>

              </div>

            ))}

          </div>

        </section>

      </main>

    </div>

  );
}